name: Actions Workflow
on: push
jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Simple JS Action
        id: simple-js-action
        uses: actions/hello-world-javascript-action@main
        with:
          who-to-greet: "Zakariae D'es"
      - name: Log Greeting Time
        run: echo "${{ steps.simple-js-action.outputs.time }}"