name: Simple Github Action
on: push
jobs:
  run-shell-commands:
    name: Running shell commands
    runs-on: ubuntu-latest
    steps:
      - name: Hello World
        run: echo "Hello World!"
      - name: Multiple Commands
        run: |
          npm -v
          node -v
      - name: Python Command
        run: |
          import Platform
          print(platform.processor())
        shell: python